#!/usr/bin/env python3
"""
Rapid Variant Evolution System
===============================

Tests multiple weight configurations rapidly to find optimal ensemble weights.

Strategy:
1. Test 5-6 weight configurations in parallel conceptually
2. Each uses proven 0D thresholds (0.75/0.70/0.65)
3. Find best performing configuration
4. Report results with accuracy breakdown

Configurations to test:
- 9A: color=0.45, raw=0.25, texture=0.15, morph=0.10, gabor=0.05 (color-focused)
- 9B: color=0.40, raw=0.30, texture=0.15, morph=0.10, gabor=0.05 (balanced)
- 9C: color=0.50, raw=0.20, texture=0.15, morph=0.10, gabor=0.05 (max color)
- 9D: color=0.35, raw=0.30, texture=0.20, morph=0.10, gabor=0.05 (texture-enhanced)
- 9E: color=0.40, raw=0.25, texture=0.20, morph=0.10, gabor=0.05 (texture-boosted)

Goal: Find configuration that achieves 95%+ on both metrics
"""

import sys
import subprocess
import re
import json
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).parent

# Weight configurations to test
CONFIGURATIONS = [
    {
        'name': '9A',
        'description': 'Color-focused (pigment discrimination)',
        'weights': {'color': 0.45, 'raw_compat': 0.25, 'texture': 0.15, 'morphological': 0.10, 'gabor': 0.05},
        'rationale': 'Pottery discrimination relies on pigment chemistry'
    },
    {
        'name': '9B',
        'description': 'Balanced (appearance + geometry)',
        'weights': {'color': 0.40, 'raw_compat': 0.30, 'texture': 0.15, 'morphological': 0.10, 'gabor': 0.05},
        'rationale': 'Balance color and geometric features for robustness'
    },
    {
        'name': '9C',
        'description': 'Maximum color weight',
        'weights': {'color': 0.50, 'raw_compat': 0.20, 'texture': 0.15, 'morphological': 0.10, 'gabor': 0.05},
        'rationale': 'Push color weight to maximum for pottery'
    },
    {
        'name': '9D',
        'description': 'Texture-enhanced',
        'weights': {'color': 0.35, 'raw_compat': 0.30, 'texture': 0.20, 'morphological': 0.10, 'gabor': 0.05},
        'rationale': 'Boost texture for surface pattern matching'
    },
    {
        'name': '9E',
        'description': 'Texture-boosted baseline',
        'weights': {'color': 0.40, 'raw_compat': 0.25, 'texture': 0.20, 'morphological': 0.10, 'gabor': 0.05},
        'rationale': 'Modest texture boost from baseline'
    },
    {
        'name': '0D',
        'description': 'Baseline (no ensemble, strict thresholds)',
        'weights': None,  # No ensemble - uses direct thresholds
        'rationale': 'Control baseline: current best (89%/86%)'
    }
]


def create_variant_module(config):
    """Create ensemble postprocess module for a configuration."""
    if config['weights'] is None:
        return None  # Use existing 0D without ensemble

    weights = config['weights']
    module_code = f'''"""
Variant {config['name']}: {config['description']}

Weights: {weights}
Rationale: {config['rationale']}

Auto-generated by rapid evolution system.
"""

import numpy as np
import logging
from typing import List, Dict, Optional
from ensemble_voting import ensemble_verdict_weighted

logger = logging.getLogger(__name__)

CUSTOM_WEIGHTS = {weights}

# Hard discriminator thresholds
HARD_DISCRIMINATOR_THRESHOLDS = {{
    'edge_density_max_diff': 0.15,
    'entropy_max_diff': 0.50,
    'min_color_similarity': 0.60,
    'min_texture_similarity': 0.55
}}


def should_skip_pair(bc_color: float, bc_texture: float,
                     edge_density_diff: float, entropy_diff: float) -> bool:
    """Pre-filter using hard discriminators."""
    if edge_density_diff > HARD_DISCRIMINATOR_THRESHOLDS['edge_density_max_diff']:
        return True
    if entropy_diff > HARD_DISCRIMINATOR_THRESHOLDS['entropy_max_diff']:
        return True
    if bc_color < HARD_DISCRIMINATOR_THRESHOLDS['min_color_similarity']:
        return True
    if bc_texture < HARD_DISCRIMINATOR_THRESHOLDS['min_texture_similarity']:
        return True
    return False


def reclassify_borderline_cases(
    assemblies: List[Dict],
    compat_matrix: np.ndarray,
    appearance_mats: Optional[Dict[str, np.ndarray]] = None,
    all_images: Optional[List[np.ndarray]] = None
) -> List[Dict]:
    """Re-classify WEAK_MATCH pairs using Variant {config['name']} configuration."""
    if appearance_mats is None or all_images is None:
        logger.warning("Ensemble post-processing skipped")
        return assemblies

    logger.info("Variant {config['name']}: {config['description']}")
    logger.info("Weights: {weights}")

    from hard_discriminators import compute_edge_density, compute_texture_entropy

    edge_densities = [compute_edge_density(img) for img in all_images]
    entropies = [compute_texture_entropy(img) for img in all_images]

    n_reclassified = 0
    n_upgraded = 0
    n_downgraded = 0

    for asm_idx, assembly in enumerate(assemblies):
        changed = False

        for pair in assembly['pairs']:
            if pair['verdict'] != 'WEAK_MATCH':
                continue

            frag_i = pair['frag_i']
            frag_j = pair['frag_j']
            raw_compat = pair['raw_compat']
            bc_color = appearance_mats['color'][frag_i, frag_j]
            bc_texture = appearance_mats['texture'][frag_i, frag_j]
            bc_gabor = appearance_mats['gabor'][frag_i, frag_j]
            edge_density_diff = abs(edge_densities[frag_i] - edge_densities[frag_j])
            entropy_diff = abs(entropies[frag_i] - entropies[frag_j])

            if should_skip_pair(bc_color, bc_texture, edge_density_diff, entropy_diff):
                ensemble_verdict = 'NO_MATCH'
            else:
                ensemble_verdict = ensemble_verdict_weighted(
                    raw_compat=raw_compat,
                    bc_color=bc_color,
                    bc_texture=bc_texture,
                    bc_gabor=bc_gabor,
                    edge_density_diff=edge_density_diff,
                    entropy_diff=entropy_diff,
                    weights=CUSTOM_WEIGHTS
                )

            if ensemble_verdict != pair['verdict']:
                n_reclassified += 1
                changed = True
                if ensemble_verdict == 'MATCH':
                    n_upgraded += 1
                elif ensemble_verdict == 'NO_MATCH':
                    n_downgraded += 1
                pair['verdict'] = ensemble_verdict

        if changed:
            assembly['verdict'] = _recompute_assembly_verdict(assembly)

    logger.info("Variant {config['name']}: Reclassified=%d, Upgraded=%d, Downgraded=%d",
               n_reclassified, n_upgraded, n_downgraded)

    return assemblies


def _recompute_assembly_verdict(assembly: Dict) -> str:
    """Recompute assembly verdict."""
    pairs = assembly['pairs']
    n_pairs = len(pairs)

    if n_pairs == 0:
        return 'NO_MATCH'

    n_match = sum(1 for p in pairs if p['verdict'] == 'MATCH')
    n_weak = sum(1 for p in pairs if p['verdict'] == 'WEAK_MATCH')
    n_valid = n_match + n_weak

    assembly['n_match'] = n_match
    assembly['n_weak'] = n_weak
    assembly['n_no_match'] = n_pairs - n_valid

    valid_ratio = n_valid / n_pairs
    match_ratio = n_match / n_pairs

    if match_ratio >= 0.40 or valid_ratio >= 0.60:
        return 'MATCH'
    elif valid_ratio >= 0.40:
        return 'WEAK_MATCH'
    else:
        return 'NO_MATCH'
'''

    module_path = ROOT / "src" / f"ensemble_postprocess_variant{config['name']}.py"
    module_path.write_text(module_code)
    return module_path


def create_variant_runner(config):
    """Create test runner for a configuration."""
    runner_code = f'''#!/usr/bin/env python3
"""
Variant {config['name']}: {config['description']}

Auto-generated by rapid evolution system.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT / "src"))

import run_test

if __name__ == "__main__":
    print("="*80)
    print("VARIANT {config['name']}: {config['description'].upper()}")
    print("="*80)
    print("Weights: {config['weights']}")
    print("Rationale: {config['rationale']}")
    print("Thresholds: Variant 0D (0.75/0.70/0.65)")
    print("="*80)
    print()

    {"import ensemble_postprocess_variant" + config['name'] if config['weights'] else "# No ensemble"}
    import relaxation_variant0D
    {"sys.modules['ensemble_postprocess'] = ensemble_postprocess_variant" + config['name'] if config['weights'] else ""}
    sys.modules['relaxation'] = relaxation_variant0D

    run_test.main()
'''

    runner_path = ROOT / f"run_variant{config['name']}.py"
    runner_path.write_text(runner_code)
    return runner_path


def parse_results(output: str) -> dict:
    """Parse test output to extract accuracies."""
    results = {'positive_accuracy': 0.0, 'negative_accuracy': 0.0, 'overall_accuracy': 0.0}

    pos_match = re.search(r'Positive Tests.*?(\d+)/(\d+).*?\((\d+(?:\.\d+)?)%\)', output, re.DOTALL)
    neg_match = re.search(r'Negative Tests.*?(\d+)/(\d+).*?\((\d+(?:\.\d+)?)%\)', output, re.DOTALL)

    if pos_match:
        results['positive_correct'] = int(pos_match.group(1))
        results['positive_total'] = int(pos_match.group(2))
        results['positive_accuracy'] = float(pos_match.group(3))

    if neg_match:
        results['negative_correct'] = int(neg_match.group(1))
        results['negative_total'] = int(neg_match.group(2))
        results['negative_accuracy'] = float(neg_match.group(3))

    if pos_match and neg_match:
        total_correct = results['positive_correct'] + results['negative_correct']
        total = results['positive_total'] + results['negative_total']
        results['overall_accuracy'] = 100.0 * total_correct / total

    return results


def test_configuration(config):
    """Test a single configuration."""
    print(f"\n{'='*80}")
    print(f"Testing Variant {config['name']}: {config['description']}")
    print(f"Weights: {config['weights']}")
    print(f"{'='*80}")

    # Create modules
    if config['name'] != '0D':
        create_variant_module(config)
        runner = create_variant_runner(config)
    else:
        runner = ROOT / "run_variant0D.py"

    # Run test
    try:
        result = subprocess.run(
            [sys.executable, str(runner)],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=450
        )

        output = result.stdout + result.stderr

        # Parse results
        results = parse_results(output)
        results.update({
            'name': config['name'],
            'description': config['description'],
            'weights': config['weights'],
            'rationale': config['rationale']
        })

        print(f"✓ Results: Pos={results.get('positive_accuracy', 0):.1f}%, "
              f"Neg={results.get('negative_accuracy', 0):.1f}%, "
              f"Overall={results.get('overall_accuracy', 0):.1f}%")

        return results

    except subprocess.TimeoutExpired:
        print(f"✗ Timeout")
        return {'name': config['name'], 'error': 'timeout'}
    except Exception as e:
        print(f"✗ Error: {e}")
        return {'name': config['name'], 'error': str(e)}


def main():
    """Main evolution loop."""
    print("="*80)
    print("RAPID VARIANT EVOLUTION SYSTEM")
    print("Target: 95%+ accuracy on both positive and negative metrics")
    print("="*80)

    results = []

    # Test all configurations
    for config in CONFIGURATIONS:
        result = test_configuration(config)
        if 'error' not in result:
            results.append(result)

    # Save results
    output_file = ROOT / "outputs" / "evolution" / f"rapid_evolution_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2)

    # Report
    print("\n" + "="*80)
    print("RAPID EVOLUTION RESULTS")
    print("="*80)

    print("\nAll Configurations (sorted by overall accuracy):")
    for r in sorted(results, key=lambda x: x.get('overall_accuracy', 0), reverse=True):
        print(f"  {r['name']:4s}: Pos={r.get('positive_accuracy', 0):5.1f}% "
              f"Neg={r.get('negative_accuracy', 0):5.1f}% "
              f"Overall={r.get('overall_accuracy', 0):5.1f}% - {r['description']}")

    # Find best
    best = max(results, key=lambda x: x.get('overall_accuracy', 0))

    print(f"\n{'='*80}")
    print(f"BEST CONFIGURATION: Variant {best['name']}")
    print(f"{'='*80}")
    print(f"Description: {best['description']}")
    print(f"Rationale: {best['rationale']}")
    print(f"Weights: {best['weights']}")
    print(f"Positive Accuracy: {best.get('positive_accuracy', 0):.1f}%")
    print(f"Negative Accuracy: {best.get('negative_accuracy', 0):.1f}%")
    print(f"Overall Accuracy: {best.get('overall_accuracy', 0):.1f}%")

    # Check if target achieved
    pos_acc = best.get('positive_accuracy', 0)
    neg_acc = best.get('negative_accuracy', 0)

    if pos_acc >= 95.0 and neg_acc >= 95.0:
        print("\n✅ TARGET ACHIEVED: 95%+ accuracy on both metrics!")
    else:
        print(f"\n⚠️ Gap to 95%: Pos={max(0, 95.0 - pos_acc):.1f}%, Neg={max(0, 95.0 - neg_acc):.1f}%")

        # Suggest next steps
        print("\nNext Steps:")
        if pos_acc < 95.0:
            print("  - Consider relaxing thresholds to improve positive recall")
        if neg_acc < 95.0:
            print("  - Consider stricter pre-filtering or ensemble gating for negative precision")

    print(f"\n✓ Results saved to: {output_file}")

    return results, best


if __name__ == "__main__":
    main()
